// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDISHgoLC6kv9SrmRgb0si83V6nIFeNIAI',
    appId: '1:905763071265:android:37990e2cdb82f5203e4a60',
    messagingSenderId: '905763071265',
    projectId: 'chat-app-b0669',
    storageBucket: 'chat-app-b0669.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdPx2l5Q76sjnKLrJKvwuWuf-qUT7Bsps',
    appId: '1:905763071265:ios:abaa8cc4f60489d43e4a60',
    messagingSenderId: '905763071265',
    projectId: 'chat-app-b0669',
    storageBucket: 'chat-app-b0669.appspot.com',
    iosClientId:
        '905763071265-lckd7ati9gcqbb7o4q1iudf6hpf6c2et.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
